dist: xenial
language: python
python:
  - "3.7"
install:
- pip install -r requirements.txt
script:
- pytest -vv --cov=./ --cov-report=xml
- codecov
- make clean docs dist
deploy:
  provider: pypi
  user: ohmrefresh
  password:
    secure: "r1FjGA8GhpfaKaTmDZyg0s37iY9ZJCBXieaJSlv9fVSvZgtOIY11xbIV6ztZru9+3BbWGsBnDPY6lOzbmW+d9bYv/txe0jn9R8PPcpevQa1+3lmtZ+KlQujUBSe+GAfcHAKCrNjDVvx+I6YtGEVt1yTCHLwl2rcNHQJxJlzkQNnqzU0iL/91rG2ztps7TjA9X6FxLaAIjimdaT8vpoV9TvIHNylI0SRfmvFYg5qhHIJLfoiFs45eKSHNjYxUcP7hnA4smLhtuLeBxDps0S66fzdzWGiY4gFQnIAq7EyT+/tM9eNag/uOlftxR3Vp1YsECiEGDeaf3IhaUnGik/WVPScY04UGNaPvoBGWKW2ISVmBharBtotqdN5LSLfFwNxXLF4QLNTtnioKQFuC3rH6is+EAEZk5nIgSa0j5+aF4jMgqpteRn0fTU10zSgwfasQBOjzN/M+rr9ahSSgnS2t+Oom14H3FoiDf/vRZPCcMqEZJbT49eCm4npM3mck3UNFoGkOx+mW3HBecwTfHwjBpFyhTL3pxnAAnR+D9OWqMCt6QRS5FwVpo6m08nqZHl3LzMXrNsWr7UAwWVMWwIOFezds9xyS6RpJtt14WP+uauxEy7yxWoZ7YCbFJiKLOJPp6+yKfvISgFksmjwuxFt91k5+0m97h2YqDwz+YknuZHE="
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: ascendcorp/grafana-snapshot